version = 1

# Exclude folders that should not be analyzed
exclude_patterns = [
  "node_modules/**",
  ".next/**",
  "out/**",
  ".deepsource.toml",
  "*.config.js",
  "*.config.ts",
  "src-tauri/target/**",
  "src-tauri/Cargo.lock"
]

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs", "browser"]
  module_system = "es-modules"
  dialect = "typescript"
  style_guide = "airbnb"
  cyclomatic_complexity_threshold = "high"
  skip_doc_coverage = ["class-expression", "method-definition"]

[[analyzers]]
name = "rust"
enabled = true
  [analyzers.meta]
  msrv = "1.70.0"

[[analyzers]]
name = "secrets"
enabled = true